### ISSUE TITLE
JuliaTokyo のロゴがほしい

### ISSUE THREAD

**Issue by yomichi** [JuliaTokyo/julia-wakalang#13]
おされフォント（Lily Script One）で書かれたのも良いけれど、Julia の3色丸をうまく活かした日本・東京っぽいロゴがほしい

**Comment by bicycle1885** [comment]
参考ロゴ

Julia Astro: https://github.com/JuliaAstro
Julia Sparse: https://github.com/JuliaSparse

**Comment by bicycle1885** [comment]
要件

* 正方形に綺麗に収まる (アイコンなどのため)
* Julia関係のロゴとすぐ分かる (3つ丸の配置や色は大きく変えない)
* 日本 and/or 東京を連想できる

で、Juliaっぽい丸っこさも維持できると良さそう。

**Comment by bicycle1885** [comment]
暫定版 (手抜きとも言う)

![untitled](https://cloud.githubusercontent.com/assets/905683/9021565/4c5b1532-3883-11e5-96b4-d5912de489bd.png)

**Comment by chezou** [comment]
ちょwww

**Comment by bicycle1885** [comment]
> デザイナーが自分は完璧に達成したんだと分かるのは、付け加えるべき
ものが何もない時ではなく、取り去るべきものが何もない時である

サン＝テグジュペリ

**Comment by yomichi** [comment]
:100:

**Comment by chezou** [comment]
よっしゃ、closeすっぞ

**Comment by chezou** [comment]
@bicycle1885 ロゴのライセンスだけ決めてくださいまし〜

**Comment by bicycle1885** [comment]
@chezou 元のロゴの改変なので継承したいけど、継承するライセンスが無い...

**Comment by chezou** [comment]
うっ...。
本家にissue立てるしかorz
