### ISSUE TITLE
もくもく会やりたい

### ISSUE THREAD

**Issue by sorami** [JuliaTokyo/julia-wakalang#17]
* 2016/02/27（土）
* 2016/03/05（土）

あたり、どうでしょう。
ブレインパッドが会場提供できると思います。

10:00~18:00、出入り自由、途中にカジュアルな発表有り、みたいな？

**Comment by sorami** [comment]
ping @chezou @bicycle1885

**Comment by bicycle1885** [comment]
:+1: どちらかと言うと27日のほうが良いです。

**Comment by chezou** [comment]
両日とも都合つかなさそうです🙏

**Comment by bicycle1885** [comment]
残念(´・ω・`) 他にやるひといるかな?

**Comment by sorami** [comment]
そういえば @oyamad さんとかも、もくもく会やりたいって言ってましたね〜。

**Comment by oyamad** [comment]
ぜひ参加したいですが，両日とも，うかがえません．すみません．．

**Comment by sorami** [comment]
そうなんですか、残念 ＞＜

**Comment by sorami** [comment]
@bicycle1885 
少人数になるかもしれませんが、 2/27（日）に開催します？

**Comment by bicycle1885** [comment]
そうですね、5~6人来れば十分だと思いますw

**Comment by sorami** [comment]
了解です、ではゆるい感じでｗ
明日、会社に連絡して、Connpassでイベント立てます〜。

**Comment by sorami** [comment]
http://juliatokyo.connpass.com/event/27257/
