### ISSUE TITLE
JuliaのMachine Learning関連のパッケージを知りたい

### ISSUE THREAD

**Issue by chezou** [JuliaTokyo/julia-wakalang#2]
できればActiveで使えるものが良い

**Comment by sorami** [comment]
[MCMC.jl](https://github.com/JuliaStats/MCMC.jl) は、気がついたら

> MCMC.jl is a placeholder for the future merge of various independent MCMC implementations in Julia, including Lora.jl.

となってました。

- [brian-j-smith/Mamba.jl](https://github.com/brian-j-smith/Mamba.jl)
- [JuliaStats/Lora.jl](https://github.com/JuliaStats/Lora.jl)
- [goedman/MCMCExampleRepository.jl](https://github.com/goedman/MCMCExampleRepository.jl)

**Comment by chezou** [comment]
@sfchaos さんによると [awesome-machine-learning](https://github.com/josephmisiti/awesome-machine-learning#julia) が良いらしい

**Comment by yutajuly** [comment]
手前味噌ですが、#JuliaTokyo3の資料[Data Science Packages](http://www.slideshare.net/yutajuly/data-science-packages)です。
これだと公式（METADATAにマージされている）のだけ扱っていますが、
[awesome-machine-learning](https://github.com/josephmisiti/awesome-machine-learning#julia)はなぜかマージされてないんですよね。なぜだ…。
