### ISSUE TITLE
ドキュメントを文字列として取得したい

### ISSUE THREAD

**Issue by machakann** [JuliaTokyo/julia-wakalang#20]
REPL の help モードで出力されるドキュメント (`help?> {keyword}`) を文字列で取得する方法はないでしょうか？

動機としては編集中にエディタの中でドキュメントをチェックしたい、というものなので文字列で取得できなくとも標準出力あたりに出してくれれば取れそうな気がします。昔のバージョン (0.3 ぐらい?) には `help()` って関数があった気がするんですがなくなったみたいです。

**Comment by yomichi** [comment]
`ret = @doc sin` とかやれば取得できます。
返ってくるのはただの`String` ではない（`Base.Markdown.MD`）ですが、とりあえず v0.6 なら `ret.content` とすれば `String` になります。

**Comment by machakann** [comment]
ありがとうございます、やりたかったことができそうです。

**Comment by machakann** [comment]
merge されるかわかりませんが、成果物です。 Vim を使っているので簡単にドキュメントを引けるようにしました。

https://github.com/JuliaEditorSupport/julia-vim/pull/139

**Comment by bicycle1885** [comment]
すばらしい！

**Comment by machakann** [comment]
上の PR が紆余曲折を経て merge されました 🎉
