### ISSUE TITLE
他ユーザーが追加したパッケージを add PKG せずに共有利用できる？

### ISSUE THREAD

**Issue by OsantaKuzune** [JuliaTokyo/julia-wakalang#27]
LinuxにrootアカウントでJulia本体をインストール後、各種パッケージを（例：pkg> **add Plots**） で追加したい場合、
ユーザーホーム(~)配下の **.julia/packages** ディレクトリにインストールされますが、
これをユーザー毎にパッケージ追加するのではなく、rootで追加し、他のユーザーが add で追加することなく、
共有利用する方法はありますでしょうか？。各ユーザーに同じパッケージを利用させ、ディスク消費量を抑えたいためです。
環境変数にヒントがありそうですがうまくいきませんでした。
環境
　OS：RHEL 7.4（CentOS 7.4) 上
　Julia：Ver. 1.5.0　インストール先：/usr/local/julia/bin

**Comment by mrkn** [comment]
環境変数 `JULIA_LOAD_PATH` [1] に root でインストールしたパッケージがインストールされているディレクトリを追加しても利用できませんか？

[1] https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_LOAD_PATH-1

**Comment by mrkn** [comment]
ちなみに、root でインストールしたパッケージが `/root/.julia` の中にインストールされていると一般ユーザから参照できないはずなので、それ以外の場所にインストールする必要があります。

そのためには、一般ユーザが読み込める場所にパッケージレジストリを置く必要があります。これを、例えば `/usr/local/julia` に置くとしたら `JULIA_DEPOT_PATH` を使って次のようにやります。

1. `mkdir -p /usr/local/julia && chmod 755 /usr/local/julia` を root で実行
2. 環境変数 `JULIA_DEPOT_PATH` に `/usr/local/julia` を設定して root で julia を実行する
3. 共有したいパッケージをインストールする
4. `chmod -R o+r /usr/local/julia` を root で実行して一般ユーザが読めるようにする

おそらく、これで準備完了です。

一般ユーザでこのディレクトリ内にインストールしたパッケージを使うには、 `JULIA_DEPT_PATH` に `~/.julia:/usr/local/julia` を設定して julia を実行し、もういちど `Pkg.add` で使いたいパッケージを自分の環境に追加します。こうすると、`~/.julia` に存在せず `/usr/local/julia` に存在するパッケージについては、 `/usr/local/julia` を参照するようになります。

**Comment by OsantaKuzune** [comment]
ご教示ありがとうございました。おかげで一般ユーザーでも参照できるようになりました。
原因は LOAD_DEPOT_PATH について理解不足で JULIA_DEPT_PATH に ~/.julia: を入れずに
/usr/local/julia だけにしていたためでした。助かりました。
