### ISSUE TITLE
今Juliaを入門するのに良いチュートリアルは？

### ISSUE THREAD

**Issue by chezou** [JuliaTokyo/julia-wakalang#3]

**Comment by chezou** [comment]
[X分で学ぶJulia - りんごがでている](http://bicycle1885.hatenablog.com/entry/2014/12/01/050522)

**Comment by chezou** [comment]
Getting Startedみたいな手を動かして学ぶのは公式が一番いいでしょうか？ @sorami @bicycle1885

**Comment by sorami** [comment]
[Seven More Languages in Seven Weeks](https://pragprog.com/book/7lang/seven-more-languages-in-seven-weeks)は良いと思います。

**Comment by sorami** [comment]
他には、 [The Julia Express](http://bogumilkaminski.pl/files/julia_express.pdf)や[Wikibooksのページ](https://en.wikibooks.org/wiki/Introducing_Julia)もなかなか良いかと。

**Comment by chezou** [comment]
あー、本という意味だと、[Getting Started with Julia](https://www.packtpub.com/application-development/getting-started-julia-programming/)も良さそうですね

**Comment by yutajuly** [comment]
日本語なら、
上で出ている[X分で学ぶJulia - りんごがでている](http://bicycle1885.hatenablog.com/entry/2014/12/01/050522)に加えて、

[JuliaTokyo #2 導入セッション]
(http://nbviewer.ipython.org/github/sorami/JuliaTokyo-2/blob/master/tutorial.ipynb)

[Julia100本ノック](https://chezou.wordpress.com/2014/06/22/julia100%E6%9C%AC%E3%83%8E%E3%83%83%E3%82%AF/)

[PythonistaのためのJulia100問100答](http://bicycle1885.hatenablog.com/entry/2014/12/23/170745)

を眺めるとだいたいイメージつきますね。

**Comment by yutajuly** [comment]
あと夜道さんのこちら。
[Julia 本Vol.1 の公開](http://yomichi.hateblo.jp/entry/2014/01/05/160714)

**Comment by yomichi** [comment]
[Learning X in Y minutes](http://learnxinyminutes.com) というサイトにもJulia のチュートリアルがあったりします。日本語訳もあります（書きました）
2013/10 の開発バージョンってどのへんかなー、って思って軽く調べたらv0.2.0rc が出たのがまさにその辺でした……時代を感じますね
さっき気づいたんだけれど、Learning Julia を今書いている Leah Hanson 氏が書いたようです
（逆に言うと夏？にLearning Juliaが出るまではまず更新されない）

**Comment by sorami** [comment]
まだ執筆途中ですが、 [chrisvoncsefalvay/learn-julia-the-hard-way](https://github.com/chrisvoncsefalvay/learn-julia-the-hard-way) も。

このChris von Csefalvayさんは、[「Julia for Data Scientists」という本を2016年夏に出版する予定だとか](http://chrisvoncsefalvay.com/scholarship/)。

**Comment by bicycle1885** [comment]
私の「X分で学ぶ~」とかを加筆修正してJupyter Notebook化しても良いかもな〜とか。
最初のステップとしては。

**Comment by chezou** [comment]
> 私の「X分で学ぶ~」とかを加筆修正してJupyter Notebook化しても良いかもな〜とか。

いいすね :+1: 
epubとかにしても面白そう

**Comment by bicycle1885** [comment]
Wikibooksの翻訳もありだと思うんですが、翻訳を追従させるのは大変だしつまらないので、1時間以内に読める分量のチュートリアルなら最初から書いた方がよいと思います。

**Comment by bicycle1885** [comment]
こんなんつくってます https://github.com/bicycle1885/Julia-Tutorial

**Comment by chezou** [comment]
@bicycle1885 ++

**Comment by chezou** [comment]
https://github.com/chezou/JuliaTokyoTutorial/blob/master/JuliaTokyo04.ipynb

DataFramesとSVMを使ったチュートリアルしました
