### ISSUE TITLE
JuliaのDeep Learning関連のパッケージを知りたい

### ISSUE THREAD

**Issue by chezou** [JuliaTokyo/julia-wakalang#4]
ref: #2

**Comment by chezou** [comment]
@bicycle1885 ping

**Comment by chezou** [comment]
- [Mocha.jl](https://github.com/pluskid/Mocha.jl)

**Comment by bicycle1885** [comment]
Minimal and fast implementation of deep learning https://github.com/denizyuret/KUnet.jl

And related read: [Beginning deep learning with 500 lines of Julia](http://www.denizyuret.com/2015/02/beginning-deep-learning-with-500-lines.html)

**Comment by r9y9** [comment]
- [Boltzmann.jl](https://github.com/dfdx/Boltzmann.jl): Restricted Boltzmann machines and deep belief networks
