### ISSUE TITLE
JuliaTokyoのchatroomが欲しい

### ISSUE THREAD

**Issue by aomoriringo** [JuliaTokyo/julia-wakalang#8]
Juliaを触り始めたばかりの初心者です。
このrepoでは「知りたいことをissueで聞く」というようになっていますが、issueをたてるまでもないようなものを気軽に質問できるように、chatroomがあれば嬉しいなと思いました。
Gitter, Slack, Lingrなどで部屋をたてるのはいかがでしょうか。
(部屋が過疎るというリスクはもちろんありますが・・・)

**Comment by chezou** [comment]
「issue立てるまでもないことでも雑に聞いていいんですよ！」っていうのがこのrepoの趣旨ではありますが、インタラクティブに進めることのメリットがあるのも理解しています。

@sorami @bicycle1885 などなどの方々、どうでしょう？

**Comment by yomichi** [comment]
ちょっとずれますが実はメーリスも存在していますね。
https://groups.google.com/forum/#!forum/julia-tokyo
まぁこちらも過疎っているわけですが……
というか、もしかしたらメーリスもここのIssue に統合しちゃうと考えたほうがいいんですかね？コード埋め込めるし。

（人がいたら）すぐに返答が返ってくるチャットと、（敷居が高い可能性があるけれど）じっくり話が進むIssue との住み分けがうまくいくと良いですね。

**Comment by sorami** [comment]
国外のコミュニティではGitterを使っている例がありますね;

- スペイン語: https://gitter.im/Ismael-VC/julialang-es
- 英語: https://gitter.im/JuliaLang/julia

---

メーリングリストやFacebookグループも一応ありますが、場所は一元化されているほうがよいと個人的には思います。

- https://groups.google.com/forum/#!forum/julia-tokyo
- https://www.facebook.com/groups/885166968160540/

メーリングリストは私以外の投稿はまだ一度もありませんし、Facebookグループはアカウントがないと使えないし、どちらも操作性がイマイチで、どうかなあと。

---

Juliaはプログラミング言語であり、興味のある方は少なからずプログラミングをされるでしょうから、GitHub（とその関連サービス）に情報を集積するのは妥当ではないでしょうか。

julia-wakalangレポジトリと、それに連携したGitter、とかが良いんでしょうかねえ。

実際にGitterを使っている方が居られたら、意見を伺いたいです。

**Comment by bicycle1885** [comment]
BioJuliaでは[Bio.jl](https://github.com/BioJulia/Bio.jl)のページにリンクがあるようにGitterがあります。
Issue立てる前に相談したりとか、学会のポスター云々とか話してますね。
そんな感じで、ここにもGitterがあると気軽で良いかもしれません。

**Comment by bicycle1885** [comment]
あ、とりあえずリンクを つ https://gitter.im/JuliaTokyo
今のところJuliaTokyoメンバーのみでしょうか。

**Comment by sorami** [comment]
@bicycle1885 BioJuliaにはメーリングリストとGitterのどちらもあるようですが、どのように使い分けているのでしょうか？

**Comment by bicycle1885** [comment]
Google Groupsのメーリスはもうずいぶん過疎ってます。アナウンスメント用などに保持しておくのは良いかもしれませんが、やはり使いづらいですね...

**Comment by chezou** [comment]
お、Boston組だ
こちらのGitterでtryということで良いですかね

https://gitter.im/JuliaTokyo/julia-wakalang

**Comment by chezou** [comment]
一旦Gitterということでcloseしますね。
何かあればReopenしましょう
